### ISSUE TITLE
All creating row spans so users can implement row grouping and other related featuers

### ISSUE THREAD

**Issue by ztoben** [glideapps/glide-data-grid#119]
Is there a way to group and collapse rows similar to how you can collapse columns?

In the same vein, is there any way to support 'label rows'? Similar to this example: https://www.w3.org/WAI/tutorials/tables/multi-level/#table-with-three-headers-related-to-each-data-cell. I don't see any `span` option, so maybe just outside of the scope of this library.

**Comment by jassmith** [comment]
row grouping with header spans are on my todo list, i will bump them and use this issue for tracking.

**Comment by jassmith** [comment]
Current working theory:

Add `span?: readonly [number, number]` to `BaseGridCell`. This would become the primary mechanism by which spans are defined. `getCellContent` to handle spans must return the same cell (by value if not by reference) for every invocation to any potential contained index inside the span.

Rendering inside `drawCells` will draw the spanned cell by de-clipping the original region and the re-clipping to the parent. The draw will happen on the first encounter of the span. There will be some mildly annoying math to find the true drawX location but whatever.

Handling keyboard interactions is more interesting. `GridSelections` which include a span do not yet have a clear indication of what should happen. I am not yet clear what the right move here is.

## Open Questions

### What should happen when you click on a span?

For the rest of this let us assume there are 20 columns, 5 can be visible at once, and the span goes for col 1 to 18. If you click on a span in col 4, my initial inclination is that the resulting `GridSelection` should be

```
{
  cell: [4, 10],
  range: { x: 1, y: 10, width: 18, height: 1 }
}
```

However this would violate one of the invariants we have inside the selection code today.

GridSelections tend to have 2 invariants:
- The selection will not flow outside the actual bounds of the data
- The cell will be at one of the corners of the range.

The second invariant being violated makes it unclear how to handle shift + arrow keys. Assuming the above `GridSelection`, Shift + Left Arrow could result in either

```
{
  cell: [4, 10],
  range: { x: 0, y: 10, width: 19, height: 1 }
}
```

or

```
{
  cell: [4, 10],
  range: { x: 1, y: 10, width: 17, height: 1 }
}
```

Both would be equally valid. Worse it seems obvious that pressing Shift + Right Arrow immediately after should essentially return to the prior state, however this would not happen regardless of which selection mode is chosen. 

### How to handle cells which should render centered in the visual space instead of the virtual space

A row group header should ensure the header name is always centered regardless of horizontal scrolling. Most other cell types however should not do such a thing.

**Comment by jassmith** [comment]
You can track progress here, for now I just put in a token commit so I could open the PR and make sure I had a checklist.

https://github.com/glideapps/glide-data-grid/pull/121

**Comment by ztoben** [comment]
Awesome, thank you! Will be following progress in the PR for sure.

**Comment by jassmith** [comment]
I have a basic version of this. Im still not happy with keyboard interactions and selection behavior. One of the problems with spans is that range selection requires a recursive search for spans and expansion phase that basically looks like this

```
while selectionContainsPartialSpan() {
  expandSelectionToContainAllSpans();
}
```

Every time you expand the selection you may end up including more partial spans. Each check pass requires an interrogative check over all cells inside the selection (well really only new ones but who is counting?). This could become quite slow with slower data sources.

**Comment by jassmith** [comment]
It's merged into 3.4.0

**Comment by ztoben** [comment]
Awesome, thank you!

**Comment by tonyxiao** [comment]
Do you have an example of implementing row grouping?
