### ISSUE TITLE
Support for pagination

### ISSUE THREAD

**Issue by png262** [glideapps/glide-data-grid#172]
For large datasets, it might not be ideal to load 1 million records from the server in one request (nor does it make sense to attempt to load all 1 million in the beginning even through pagination), so is it possible to extend the API to provide a "load more" callback so that it can trigger subsequent pagination requests from server? 

I am thinking the callback would trigger when the user has reached the bottom of the grid, similar to how infinite scrolling works

**Comment by jassmith** [comment]
We do this all the time in our usage of GDG. The solution here is pretty simply. You are given the visible window, decide how much you want to preload and always load at least that much, then just watch for visible window changes. There is a story in storybook that shows how to watch the visible window. The `getCellContent` callback identity should change if and only if you end up loading things already visible, otherwise you can leave the identity as is and avoid the re-render. Or just let it rerender each time you load more data you probably wont notice the difference.

**Comment by TanishJain1510** [comment]
how to use  visible window because it is not giving me a way to detect the user has scroll to the end 
and thus I am unable to add pagination functionality like infinite scroll .
kindly help me .

**Comment by octavian-ene** [comment]
> how to use visible window because it is not giving me a way to detect the user has scroll to the end and thus I am unable to add pagination functionality like infinite scroll . kindly help me .

+1 I would love to know as well. Maybe a clear cut example on the storybook would be fine!
