### ISSUE TITLE
Not sure how to use a remote api

### ISSUE THREAD

**Issue by ScarletJack** [glideapps/glide-data-grid#281]
I've been trying to follow [this ](https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--server-side-data)example using the and I've almost got it working using the [swapi.dev ](https://swapi.dev/api/people)api, but there seems to be some kind of rendering/paint issue on my side that I can't figure out. Displayed here:

https://user-images.githubusercontent.com/68049836/164431740-334a79f0-06ab-4be5-bb9e-b5ae082f6466.mp4
(Apologies for the lengthy fetch time)

The data is available to the grid but only after clicking or scrolling do the cells update. 

This is also fixed if you manually call `updateCells`

[Here's a link to a codesandbox](https://codesandbox.io/s/new-shape-vun7cr?file=/src/adapter.ts) that I tried to build (I'm not sure why it's not working on Codesandbox, works on my storybook)

Is there some kind of issue or am I just not doing it right?

**Comment by jassmith** [comment]
I haven't fully dug into it, I moved it over to stackblitz because they dont have the enum bug currently impacting codesandbox. Long story short you are calling to swapi with page=0 when it is not zero indexed. You are also not being careful about how you pack the array so things can get very out of order.

You also seem to have some kind of a remounting issue going on. Have you considered just using the pre-built async data source in the @glideapps/glide-data-grid-source package?

**Comment by jassmith** [comment]
Im closing this for now, please re-open if you are unable to make more progress.
