### ISSUE TITLE
When scroll after entering edit-mode in cells, the popup does not stay with the cell

### ISSUE THREAD

**Issue by janwirth** [glideapps/glide-data-grid#583]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/7485959/210161665-07281a34-5fc7-4dcd-8558-2c387f54f8a7.png">
**Actual**
The cell is staying as I scroll and the grid moves

**Expected**
The cell scrolls with the table.

This happens both when scrolling the grid as well as when scrolling the page around the grid.

**Idea**
Floating UI has "Virtual Elements" that allow you to position a floating element relative to an arbitrary bounding box.

https://floating-ui.com/docs/virtual-elements

**Comment by yusufkinatas** [comment]
To overcome this issue, we locked the scroll of the page when editor overlays are open. But we only did that for custom cells, since on our use case, only our custom cells had editor overlays. Maybe giving "locking page scroll" a try could be helpful.

**Comment by jassmith** [comment]
This was an intentional design decision. Forcing the scrolling to stay in sync comes with 2 major issues:

1) The overlay isn't really cropped, it would keep scrolling even as the cell went out of view. Fixable but annoying.  
2) It makes it so you can't open an overlay, then scroll a couple pages to reference something else for data entry purposes.

**Comment by jassmith** [comment]
I'd be open to a PR for this as an option.

**Comment by janwirth** [comment]
Thank you for elaborating. Not really an issue for me. Feel free to close.

**Comment by ronnyek** [comment]
I've recently run into this, and I've gotta say... this is a really really minor thing, that I think is more an inconvenience than anything else. My fear is that this could lead to confusing user experience. In thinking it out, I don't think that the confusion would be resolved even if anchoring the portal to the cell somehow became possible. (User could initiate the edit, and then scroll the edited cell out of the viewport, but still be in edit mode... and simply focusing something else could essentially save that change in a not so obvious way).

I'm curious about opinions on two things
- Would a reasonable solution be to somehow lock scrolling of the grid while editing is happening (could see negatives and positives here)
- As I understand all editing components (custom or otherwise) render into a portal. Could there be an option to just render a component that manages its own popups in place of the non-edit cell with a flag or something? (would that introduce performance issues or cause extra unnecessary redraws?)

I'd potentially be interested in at least looking into this more, and potentially providing a PR, because as I see it, this grid fits a LOT of needs and seems to do things in a rather efficient way.
