### ISSUE TITLE
How do I programmatically clear the user selection?

### ISSUE THREAD

**Issue by craigjohnson123** [glideapps/glide-data-grid#786]
Still fairly new to Reactjs and glide-data-grid. 
I've set row markers, and users are able to select rows.  I've also added a filtering capability.
I'd like to programmatically clear the selection when users filter the data. 
Thanks

**Comment by jassmith** [comment]
hey no problem. In general you the data grid work similar to how a react `input` works, just a lot more complex.

So with an input you would do something like.

```ts
import React, { useState } from 'react';

function Example() {
  const [inputValue, setInputValue] = useState(''); // Initialize with an empty string

  const handleChange = (event) => {
    setInputValue(event.target.value); // Update the state with the input's current value
  }

  return (
    <div>
      <input 
        type="text"
        value={inputValue}
        onChange={handleChange}
      />
      <p>Typed value: {inputValue}</p>
    </div>
  );
}
```

The primary difference with the data grid is that instead of value and onChange you use gridSelection and onGridSelectionChange. The values in the `gridSelection` you are looking for are stored in the `rows` property. You can also reset the `gridSelection` to undefined when you start filtering.
