### ISSUE TITLE
Select all rows functionality doesn't return the right values in onGridSelectionChange callback

### ISSUE THREAD

**Issue by ajejoseph22** [glideapps/glide-data-grid#824]
I have the following code

```
<Grid
    ...
    onGridSelectionChange={(sel) => {
      console.log("sel.rows", sel.rows);
      set_selection(sel);
    }}
    gridSelection={selection}
    ...
/>
```

When I select individual rows, the console.log in onGridSelectionChange callback logs the right values. 
e.g 
```
{
  ...
  rows: _CompactSelection {items: Array(N)} // where N is number fo rows
  ...
}
```
However, when I use the "select all" button, the callback returns only one item (usually the last item), so in a table of say 1000 items the result is like this

```
{
  ...
  rows: _CompactSelection {items: Array(1)} // where items array is [999, 1000]
  ...
}
```

Ideally this should be an array of all the values (1000 items)

**Comment by jassmith** [comment]
As best I can tell this is working correctly. When you select the top checkbox in all my test cases an event is emitted with the rows set to a compact selection with 1 item marked as [0, 1000] (assuming 1000 rows). We use compact selections not a straight array otherwise the select all button would allocate an unreasonably large amount of memory on large grids. If you really want the compact selection as a fully inflated array there is a .toArray method.

**Comment by ajejoseph22** [comment]
Gotcha. Thanks for the clarification @jassmith
