### ISSUE TITLE
Getting blank view while rendering more than 480 rows

### ISSUE THREAD

**Issue by samya-ak** [glideapps/glide-data-grid#944]
### Issue:
I'm getting blank view in firefox when trying to render more than 480 rows. Chrome seems to be able to render around 965 rows.

![image](https://github.com/glideapps/glide-data-grid/assets/38690337/9d6f1130-80fe-476c-9838-8ffa3c51ddad)

Cells are editable though.

<img width="760" alt="Screenshot 2024-04-15 at 9 11 59 PM" src="https://github.com/glideapps/glide-data-grid/assets/38690337/96fde08f-e584-476f-ab8c-5798002fe15f">

### Error in Firefox:
[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: ".../node_modules/@glideapps/glide-data-grid/dist/cjs/internal/data-grid/render/data-grid-render.js :: drawGrid :: line 131"  data: no]

### Code Sandbox:
https://codesandbox.io/p/sandbox/xenodochial-rubin-mwj46c?file=%2Fsrc%2FGlide.tsx%3A101%2C35

Node version: 20.12.1
React version: 18.2.0
Glide data grid version: 6.0.3

I'm trying to render thousands of rows from an excel file. I've tried using the hook `useAsyncData` from [here](https://github.com/glideapps/glide-data-grid/blob/e79e8983cc2e297206ee5185441ca4edd1dcba47/packages/core/src/docs/examples/server-side-data.stories.tsx#L35). But, I'm getting the blank view when number of rows cross said threshold.

I would appreciate if someone could point out the right way to render huge number of rows.

Thanks!

**Comment by JYeeRen** [comment]
I tested your code and I suspect that it's because the canvas is too large, which caused issues. After setting a height, it worked normally `<DataEditor height={500} ... />`. Alternatively, `<DataEditor height={window.innerHeight} ... />` also works. Additionally, I think that when the table height exceeds the screen height, the excess part doesn't make sense, as it can't be seen outside of the screen anyway.

A canvas with a height of 44,000px（1000x44） may be too large for the browser.
